# style.d2

classes: {
    cto: {
        style {
        fill: "#ff7675" 
        stroke: "#d63031" 
        shadow: true 
        border-radius: 8 
        font-size: 28
      }
    }
  
    schema: {
      style {
      fill: "#fab1a0" 
      stroke: "#e17055" 
      shadow: true 
      border-radius: 8 
      font-size: 28
    }
  }
  
  nfdicore: {
    style {
    fill: "#81ecec" 
    stroke: "#00cec9" 
    shadow: true 
    border-radius: 8
    font-size: 28 
  }
  }
  
  iao: {
    style {
    fill: "#ffeaa7" 
    stroke: "#fdcb6e" 
    shadow: true 
    border-radius: 8 
    font-size: 28
  }
  }
  
  bfo: {
    style {
    fill: "#74b9ff" 
    stroke: "#0984e3" 
    shadow: true 
    border-radius: 8 
    font-size: 28
  }
  }
  
  literal:{
    style {
    stroke-dash: 4
    stroke: "#2d3436"
    font-size: 28
  }
  }
  
  entity:{
      style {
      font-size: 28
    }
    }
  
  edge_type: {
      style: {
        stroke-dash: 2    
        stroke: "#636e72"
        font-size: 28
    }
    }
    
  edge_subclass: {
      style: {
        stroke-dash: 4    
        stroke: "#636e72"
        font-size: 28
    }
    }
  
  edge_other: {
      style: {
        stroke: "#636e72"
        font-size: 28
    }
    }
   
  
  }