site_name: NFDI4Culture
site_url: https://nfdi.fiz-karlsruhe.de/4culture/
repo_url: https://github.com/ISE-FIZKarlsruhe/nfdi4culture
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
  hide:
    - toc
nav:
  - Intro and Metadata: index.md
  - Widoco Documentation: /4culture/ontology/
  - NFDI Context: nfdi-context.md
  - Scope and Structure: structure.md
  #- Patterns: patterns.md
  - Domain Examples: domain-examples.md
  - References: references.md

#  - Sample Applications: rdg.md
#  - Sample Queries: queries.md
#  - Tools:
#      - Hydra Scraper: hydra.md
#      - OAI-Harvesting: oai.md
#  - Data Sources:
#      - Misc: datasources.md
#      - DDB: ddb.md
#      - Factgrid: factgrid.md

markdown_extensions:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format


plugins:
  - d2
